name: install and test
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 21.x, 22.x, 23.x, 24.x]

        steps:
            - name: Install libcrack2
              run: sudo apt-get install libcrack2 libcrack2-dev
            - uses: actions/checkout@v3
            - name: Using nodejs $ {{ matrix.node-version }}
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - name: Run unit tests
              run: npm test
